# https://taskfile.dev

version: '3'

vars:
  FILE: main/main.go

tasks:
  build:
    cmds:
      -  go build -o dist/labs main/main.go
    silent: true

  build-all-os:
    desc: Build for all os
    cmds:
      - GOOS=linux GOARCH=amd64 go build  -o dist/linux/labs  {{.FILE}}
      - GOOS=windows GOARCH=amd64 go build -o dist/windows/labs.exe  {{.FILE}} 
      - GOOS=darwin GOARCH=amd64 go build -o dist/mac/labs  {{.FILE}} 

  test:
    deps: [build]
    sources: 
      - ./*.go
      - main/*go
    desc: go test
    cmds:
      - clear
      - date
      - go test -v

  testrun-zero:
    desc: run testcycle
    cmds:
      - echo "Lab with all parameters"
      - go run main/main.go destroy -l 0
      - go run main/main.go deploy -l 0
      - go run main/main.go destroy -l 0

  testrun:
    desc: run testcycle
    cmds:
      - echo "Lab with all parameters"
      - go run main/main.go destroy -l 0
      - go run main/main.go deploy -l 0
      - sleep 5
      - go run main/main.go destroy -l 0
      - echo "Lab with one parameters"
      - go run main/main.go destroy -l 1
      - go run main/main.go deploy -l 1
      - sleep 5
      - go run main/main.go destroy -l 1
    ignore_error: true

  install-local:
    desc: Install in "user/local/bin"
    deps: [build]
    cmds: 
      - sudo cp dist/mac/labs /usr/local/bin/labs
